// Generated by jextract

package tech.bitey.golpanama.xutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$68 {

    static final FunctionDescriptor XCloseIM$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XCloseIM$MH = RuntimeHelper.downcallHandle(
        "XCloseIM",
        constants$68.XCloseIM$FUNC, false
    );
    static final FunctionDescriptor XGetIMValues$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XGetIMValues$MH = RuntimeHelper.downcallHandle(
        "XGetIMValues",
        constants$68.XGetIMValues$FUNC, true
    );
    static final FunctionDescriptor XSetIMValues$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XSetIMValues$MH = RuntimeHelper.downcallHandle(
        "XSetIMValues",
        constants$68.XSetIMValues$FUNC, true
    );
    static final FunctionDescriptor XDisplayOfIM$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XDisplayOfIM$MH = RuntimeHelper.downcallHandle(
        "XDisplayOfIM",
        constants$68.XDisplayOfIM$FUNC, false
    );
    static final FunctionDescriptor XLocaleOfIM$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XLocaleOfIM$MH = RuntimeHelper.downcallHandle(
        "XLocaleOfIM",
        constants$68.XLocaleOfIM$FUNC, false
    );
    static final FunctionDescriptor XCreateIC$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XCreateIC$MH = RuntimeHelper.downcallHandle(
        "XCreateIC",
        constants$68.XCreateIC$FUNC, true
    );
}


