// Generated by jextract

package tech.bitey.golpanama.xutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$51 {

    static final FunctionDescriptor XSetBackground$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetBackground$MH = RuntimeHelper.downcallHandle(
        "XSetBackground",
        constants$51.XSetBackground$FUNC, false
    );
    static final FunctionDescriptor XSetClipMask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetClipMask$MH = RuntimeHelper.downcallHandle(
        "XSetClipMask",
        constants$51.XSetClipMask$FUNC, false
    );
    static final FunctionDescriptor XSetClipOrigin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XSetClipOrigin$MH = RuntimeHelper.downcallHandle(
        "XSetClipOrigin",
        constants$51.XSetClipOrigin$FUNC, false
    );
    static final FunctionDescriptor XSetClipRectangles$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XSetClipRectangles$MH = RuntimeHelper.downcallHandle(
        "XSetClipRectangles",
        constants$51.XSetClipRectangles$FUNC, false
    );
    static final FunctionDescriptor XSetCloseDownMode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XSetCloseDownMode$MH = RuntimeHelper.downcallHandle(
        "XSetCloseDownMode",
        constants$51.XSetCloseDownMode$FUNC, false
    );
    static final FunctionDescriptor XSetCommand$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XSetCommand$MH = RuntimeHelper.downcallHandle(
        "XSetCommand",
        constants$51.XSetCommand$FUNC, false
    );
}


