// Generated by jextract

package tech.bitey.golpanama.xutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$86 {

    static final MemorySegment XNBaseFontName$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("baseFontName");
    static final MemorySegment XNOMAutomatic$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("omAutomatic");
    static final MemorySegment XNMissingCharSet$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("missingCharSet");
    static final MemorySegment XNDefaultString$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("defaultString");
    static final MemorySegment XNOrientation$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("orientation");
    static final MemorySegment XNDirectionalDependentDrawing$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("directionalDependentDrawing");
}


