// Generated by jextract

package tech.bitey.golpanama.xutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$18 {

    static final FunctionDescriptor XIOErrorHandler$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XIOErrorHandler$MH = RuntimeHelper.downcallHandle(
        constants$18.XIOErrorHandler$FUNC, false
    );
    static final FunctionDescriptor XSetIOErrorHandler$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XSetIOErrorHandler$MH = RuntimeHelper.downcallHandle(
        "XSetIOErrorHandler",
        constants$18.XSetIOErrorHandler$FUNC, false
    );
    static final FunctionDescriptor XListPixmapFormats$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XListPixmapFormats$MH = RuntimeHelper.downcallHandle(
        "XListPixmapFormats",
        constants$18.XListPixmapFormats$FUNC, false
    );
    static final FunctionDescriptor XListDepths$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XListDepths$MH = RuntimeHelper.downcallHandle(
        "XListDepths",
        constants$18.XListDepths$FUNC, false
    );
    static final FunctionDescriptor XReconfigureWMWindow$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XReconfigureWMWindow$MH = RuntimeHelper.downcallHandle(
        "XReconfigureWMWindow",
        constants$18.XReconfigureWMWindow$FUNC, false
    );
    static final FunctionDescriptor XGetWMProtocols$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XGetWMProtocols$MH = RuntimeHelper.downcallHandle(
        "XGetWMProtocols",
        constants$18.XGetWMProtocols$FUNC, false
    );
}


