// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _XIMPreeditStateNotifyCallbackStruct {
 *     XIMPreeditState state;
 * };
 * }
 */
public class _XIMPreeditStateNotifyCallbackStruct {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("state")
    ).withName("_XIMPreeditStateNotifyCallbackStruct");
    public static MemoryLayout $LAYOUT() {
        return _XIMPreeditStateNotifyCallbackStruct.$struct$LAYOUT;
    }
    static final VarHandle state$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("state"));
    public static VarHandle state$VH() {
        return _XIMPreeditStateNotifyCallbackStruct.state$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * XIMPreeditState state;
     * }
     */
    public static long state$get(MemorySegment seg) {
        return (long)_XIMPreeditStateNotifyCallbackStruct.state$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * XIMPreeditState state;
     * }
     */
    public static void state$set(MemorySegment seg, long x) {
        _XIMPreeditStateNotifyCallbackStruct.state$VH.set(seg, x);
    }
    public static long state$get(MemorySegment seg, long index) {
        return (long)_XIMPreeditStateNotifyCallbackStruct.state$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void state$set(MemorySegment seg, long index, long x) {
        _XIMPreeditStateNotifyCallbackStruct.state$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


