// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final VarHandle const$0 = constants$84.const$5.varHandle(MemoryLayout.PathElement.groupElement("place"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("serial"),
        JAVA_INT.withName("send_event"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("display"),
        JAVA_LONG.withName("parent"),
        JAVA_LONG.withName("window"),
        JAVA_INT.withName("place"),
        MemoryLayout.paddingLayout(4)
    ).withName("");
    static final VarHandle const$2 = constants$86.const$1.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$3 = constants$86.const$1.varHandle(MemoryLayout.PathElement.groupElement("serial"));
    static final VarHandle const$4 = constants$86.const$1.varHandle(MemoryLayout.PathElement.groupElement("send_event"));
    static final VarHandle const$5 = constants$86.const$1.varHandle(MemoryLayout.PathElement.groupElement("display"));
}


