// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$227 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$227() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "XGetWMName",
        constants$149.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "XGetWMNormalHints",
        constants$146.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "XGetWMSizeHints",
        constants$225.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "XGetZoomHints",
        constants$149.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "XIntersectRegion",
        constants$113.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "XConvertCase",
        constants$227.const$5
    );
}


