// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final VarHandle const$0 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("serial"));
    static final VarHandle const$1 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("send_event"));
    static final VarHandle const$2 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("display"));
    static final VarHandle const$3 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("window"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("serial"),
        JAVA_INT.withName("send_event"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("display"),
        JAVA_LONG.withName("window"),
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("width"),
        JAVA_INT.withName("height"),
        JAVA_INT.withName("count"),
        MemoryLayout.paddingLayout(4)
    ).withName("");
    static final VarHandle const$5 = constants$61.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


