// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final VarHandle const$0 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("font"));
    static final VarHandle const$1 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("subwindow_mode"));
    static final VarHandle const$2 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("graphics_exposures"));
    static final VarHandle const$3 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("clip_x_origin"));
    static final VarHandle const$4 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("clip_y_origin"));
    static final VarHandle const$5 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("clip_mask"));
}


