// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$88 {

    static final MemorySegment XNFocusWindow$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("focusWindow");
    static final MemorySegment XNResourceName$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("resourceName");
    static final MemorySegment XNResourceClass$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("resourceClass");
    static final MemorySegment XNGeometryCallback$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("geometryCallback");
    static final MemorySegment XNDestroyCallback$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("destroyCallback");
    static final MemorySegment XNFilterEvents$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("filterEvents");
}


