// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final FunctionDescriptor XClipBox$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XClipBox$MH = RuntimeHelper.downcallHandle(
        "XClipBox",
        constants$74.XClipBox$FUNC
    );
    static final FunctionDescriptor XCreateRegion$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle XCreateRegion$MH = RuntimeHelper.downcallHandle(
        "XCreateRegion",
        constants$74.XCreateRegion$FUNC
    );
    static final FunctionDescriptor XDefaultString$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle XDefaultString$MH = RuntimeHelper.downcallHandle(
        "XDefaultString",
        constants$74.XDefaultString$FUNC
    );
    static final FunctionDescriptor XDeleteContext$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XDeleteContext$MH = RuntimeHelper.downcallHandle(
        "XDeleteContext",
        constants$74.XDeleteContext$FUNC
    );
    static final FunctionDescriptor XDestroyRegion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XDestroyRegion$MH = RuntimeHelper.downcallHandle(
        "XDestroyRegion",
        constants$74.XDestroyRegion$FUNC
    );
    static final FunctionDescriptor XEmptyRegion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XEmptyRegion$MH = RuntimeHelper.downcallHandle(
        "XEmptyRegion",
        constants$74.XEmptyRegion$FUNC
    );
}


