// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("ext_data"),
        JAVA_INT.withName("depth"),
        JAVA_INT.withName("bits_per_pixel"),
        JAVA_INT.withName("scanline_pad"),
        MemoryLayout.paddingLayout(4)
    ).withName("");
    static final VarHandle const$1 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("ext_data"));
    static final VarHandle const$2 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("depth"));
    static final VarHandle const$3 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("bits_per_pixel"));
    static final VarHandle const$4 = constants$23.const$0.varHandle(MemoryLayout.PathElement.groupElement("scanline_pad"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_LONG.withName("background_pixmap"),
        JAVA_LONG.withName("background_pixel"),
        JAVA_LONG.withName("border_pixmap"),
        JAVA_LONG.withName("border_pixel"),
        JAVA_INT.withName("bit_gravity"),
        JAVA_INT.withName("win_gravity"),
        JAVA_INT.withName("backing_store"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("backing_planes"),
        JAVA_LONG.withName("backing_pixel"),
        JAVA_INT.withName("save_under"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("event_mask"),
        JAVA_LONG.withName("do_not_propagate_mask"),
        JAVA_INT.withName("override_redirect"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("colormap"),
        JAVA_LONG.withName("cursor")
    ).withName("");
}


