// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final FunctionDescriptor XSetTile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetTile$MH = RuntimeHelper.downcallHandle(
        "XSetTile",
        constants$55.XSetTile$FUNC
    );
    static final FunctionDescriptor XSetWindowBackground$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetWindowBackground$MH = RuntimeHelper.downcallHandle(
        "XSetWindowBackground",
        constants$55.XSetWindowBackground$FUNC
    );
    static final FunctionDescriptor XSetWindowBackgroundPixmap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetWindowBackgroundPixmap$MH = RuntimeHelper.downcallHandle(
        "XSetWindowBackgroundPixmap",
        constants$55.XSetWindowBackgroundPixmap$FUNC
    );
    static final FunctionDescriptor XSetWindowBorder$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetWindowBorder$MH = RuntimeHelper.downcallHandle(
        "XSetWindowBorder",
        constants$55.XSetWindowBorder$FUNC
    );
    static final FunctionDescriptor XSetWindowBorderPixmap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XSetWindowBorderPixmap$MH = RuntimeHelper.downcallHandle(
        "XSetWindowBorderPixmap",
        constants$55.XSetWindowBorderPixmap$FUNC
    );
    static final FunctionDescriptor XSetWindowBorderWidth$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XSetWindowBorderWidth$MH = RuntimeHelper.downcallHandle(
        "XSetWindowBorderWidth",
        constants$55.XSetWindowBorderWidth$FUNC
    );
}


