// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final VarHandle const$0 = constants$107.const$5.varHandle(MemoryLayout.PathElement.groupElement("chars"));
    static final VarHandle const$1 = constants$107.const$5.varHandle(MemoryLayout.PathElement.groupElement("nchars"));
    static final VarHandle const$2 = constants$107.const$5.varHandle(MemoryLayout.PathElement.groupElement("delta"));
    static final VarHandle const$3 = constants$107.const$5.varHandle(MemoryLayout.PathElement.groupElement("font"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("byte1"),
        JAVA_BYTE.withName("byte2")
    ).withName("");
    static final VarHandle const$5 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("byte1"));
}


