// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$29 {

    static final FunctionDescriptor XDoesSaveUnders$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XDoesSaveUnders$MH = RuntimeHelper.downcallHandle(
        "XDoesSaveUnders",
        constants$29.XDoesSaveUnders$FUNC, false
    );
    static final FunctionDescriptor XDisableAccessControl$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XDisableAccessControl$MH = RuntimeHelper.downcallHandle(
        "XDisableAccessControl",
        constants$29.XDisableAccessControl$FUNC, false
    );
    static final FunctionDescriptor XDisplayCells$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XDisplayCells$MH = RuntimeHelper.downcallHandle(
        "XDisplayCells",
        constants$29.XDisplayCells$FUNC, false
    );
    static final FunctionDescriptor XDisplayHeight$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XDisplayHeight$MH = RuntimeHelper.downcallHandle(
        "XDisplayHeight",
        constants$29.XDisplayHeight$FUNC, false
    );
    static final FunctionDescriptor XDisplayHeightMM$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XDisplayHeightMM$MH = RuntimeHelper.downcallHandle(
        "XDisplayHeightMM",
        constants$29.XDisplayHeightMM$FUNC, false
    );
    static final FunctionDescriptor XDisplayKeycodes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XDisplayKeycodes$MH = RuntimeHelper.downcallHandle(
        "XDisplayKeycodes",
        constants$29.XDisplayKeycodes$FUNC, false
    );
}


