// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    static final VarHandle const$0 = constants$82.const$2.varHandle(MemoryLayout.PathElement.groupElement("display"));
    static final VarHandle const$1 = constants$82.const$2.varHandle(MemoryLayout.PathElement.groupElement("parent"));
    static final VarHandle const$2 = constants$82.const$2.varHandle(MemoryLayout.PathElement.groupElement("window"));
    static final VarHandle const$3 = constants$82.const$2.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$4 = constants$82.const$2.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$5 = constants$82.const$2.varHandle(MemoryLayout.PathElement.groupElement("width"));
}


