// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    static final MemorySegment XNStringConversion$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("stringConversion");
    static final MemorySegment XNResetState$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("resetState");
    static final MemorySegment XNHotKey$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("hotKey");
    static final MemorySegment XNHotKeyState$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("hotKeyState");
    static final MemorySegment XNPreeditState$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("preeditState");
    static final MemorySegment XNSeparatorofNestedList$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("separatorofNestedList");
}


