// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$21 {

    static final FunctionDescriptor XAddToSaveSet$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XAddToSaveSet$MH = RuntimeHelper.downcallHandle(
        "XAddToSaveSet",
        constants$21.XAddToSaveSet$FUNC
    );
    static final FunctionDescriptor XAllocColor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XAllocColor$MH = RuntimeHelper.downcallHandle(
        "XAllocColor",
        constants$21.XAllocColor$FUNC
    );
    static final FunctionDescriptor XAllocColorCells$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XAllocColorCells$MH = RuntimeHelper.downcallHandle(
        "XAllocColorCells",
        constants$21.XAllocColorCells$FUNC
    );
    static final FunctionDescriptor XAllocColorPlanes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XAllocColorPlanes$MH = RuntimeHelper.downcallHandle(
        "XAllocColorPlanes",
        constants$21.XAllocColorPlanes$FUNC
    );
    static final FunctionDescriptor XAllocNamedColor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XAllocNamedColor$MH = RuntimeHelper.downcallHandle(
        "XAllocNamedColor",
        constants$21.XAllocNamedColor$FUNC
    );
    static final FunctionDescriptor XAllowEvents$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle XAllowEvents$MH = RuntimeHelper.downcallHandle(
        "XAllowEvents",
        constants$21.XAllowEvents$FUNC
    );
}


