// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("extension"));
    static final VarHandle const$1 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("major_opcode"));
    static final VarHandle const$2 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("first_event"));
    static final VarHandle const$3 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("first_error"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("depth"),
        JAVA_INT.withName("bits_per_pixel"),
        JAVA_INT.withName("scanline_pad")
    ).withName("");
    static final VarHandle const$5 = constants$12.const$4.varHandle(MemoryLayout.PathElement.groupElement("depth"));
}


