// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$75 {

    static final MemorySegment XNDirectionalDependentDrawing$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("directionalDependentDrawing");
    static final MemorySegment XNContextualDrawing$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("contextualDrawing");
    static final MemorySegment XNFontInfo$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("fontInfo");
    static final MemorySegment XNVaNestedList$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("XNVaNestedList");
    static final MemorySegment XNQueryInputStyle$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("queryInputStyle");
    static final MemorySegment XNClientWindow$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("clientWindow");
}


