// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$193 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$193() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "XTextExtents16",
        constants$192.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "XTextWidth",
        constants$148.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "XTextWidth16",
        constants$148.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "XTranslateCoordinates",
        constants$193.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "XUndefineCursor",
        constants$38.const$0
    );
}


