// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$215 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$215() {}
    static final VarHandle const$0 = constants$214.const$0.varHandle(MemoryLayout.PathElement.groupElement("icon_x"));
    static final VarHandle const$1 = constants$214.const$0.varHandle(MemoryLayout.PathElement.groupElement("icon_y"));
    static final VarHandle const$2 = constants$214.const$0.varHandle(MemoryLayout.PathElement.groupElement("icon_mask"));
    static final VarHandle const$3 = constants$214.const$0.varHandle(MemoryLayout.PathElement.groupElement("window_group"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("value"),
        JAVA_LONG.withName("encoding"),
        JAVA_INT.withName("format"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("nitems")
    ).withName("");
    static final VarHandle const$5 = constants$215.const$4.varHandle(MemoryLayout.PathElement.groupElement("value"));
}


