// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$107() {}
    static final VarHandle const$0 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("n_properties"));
    static final VarHandle const$1 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("properties"));
    static final VarHandle const$2 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("per_char"));
    static final VarHandle const$3 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("ascent"));
    static final VarHandle const$4 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("descent"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("chars"),
        JAVA_INT.withName("nchars"),
        JAVA_INT.withName("delta"),
        JAVA_LONG.withName("font")
    ).withName("");
}


