// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final VarHandle const$0 = constants$32.const$0.varHandle(MemoryLayout.PathElement.groupElement("bits_per_pixel"));
    static final VarHandle const$1 = constants$32.const$0.varHandle(MemoryLayout.PathElement.groupElement("red_mask"));
    static final VarHandle const$2 = constants$32.const$0.varHandle(MemoryLayout.PathElement.groupElement("green_mask"));
    static final VarHandle const$3 = constants$32.const$0.varHandle(MemoryLayout.PathElement.groupElement("blue_mask"));
    static final VarHandle const$4 = constants$32.const$0.varHandle(MemoryLayout.PathElement.groupElement("obdata"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("create_image"),
        RuntimeHelper.POINTER.withName("destroy_image"),
        RuntimeHelper.POINTER.withName("get_pixel"),
        RuntimeHelper.POINTER.withName("put_pixel"),
        RuntimeHelper.POINTER.withName("sub_image"),
        RuntimeHelper.POINTER.withName("add_pixel")
    ).withName("funcs");
}


