// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$49 {

    static final FunctionDescriptor XRemoveHosts$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XRemoveHosts$MH = RuntimeHelper.downcallHandle(
        "XRemoveHosts",
        constants$49.XRemoveHosts$FUNC, false
    );
    static final FunctionDescriptor XReparentWindow$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XReparentWindow$MH = RuntimeHelper.downcallHandle(
        "XReparentWindow",
        constants$49.XReparentWindow$FUNC, false
    );
    static final FunctionDescriptor XResetScreenSaver$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XResetScreenSaver$MH = RuntimeHelper.downcallHandle(
        "XResetScreenSaver",
        constants$49.XResetScreenSaver$FUNC, false
    );
    static final FunctionDescriptor XResizeWindow$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XResizeWindow$MH = RuntimeHelper.downcallHandle(
        "XResizeWindow",
        constants$49.XResizeWindow$FUNC, false
    );
    static final FunctionDescriptor XRestackWindows$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XRestackWindows$MH = RuntimeHelper.downcallHandle(
        "XRestackWindows",
        constants$49.XRestackWindows$FUNC, false
    );
    static final FunctionDescriptor XRotateBuffers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XRotateBuffers$MH = RuntimeHelper.downcallHandle(
        "XRotateBuffers",
        constants$49.XRotateBuffers$FUNC, false
    );
}


