// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final VarHandle const$0 = constants$53.const$4.varHandle(MemoryLayout.PathElement.groupElement("time"));
    static final VarHandle const$1 = constants$53.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$2 = constants$53.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$3 = constants$53.const$4.varHandle(MemoryLayout.PathElement.groupElement("x_root"));
    static final VarHandle const$4 = constants$53.const$4.varHandle(MemoryLayout.PathElement.groupElement("y_root"));
    static final VarHandle const$5 = constants$53.const$4.varHandle(MemoryLayout.PathElement.groupElement("state"));
}


