// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$4 {

    static final FunctionDescriptor XInitImage$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XInitImage$MH = RuntimeHelper.downcallHandle(
        "XInitImage",
        constants$4.XInitImage$FUNC, false
    );
    static final FunctionDescriptor XGetImage$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XGetImage$MH = RuntimeHelper.downcallHandle(
        "XGetImage",
        constants$4.XGetImage$FUNC, false
    );
    static final FunctionDescriptor XGetSubImage$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle XGetSubImage$MH = RuntimeHelper.downcallHandle(
        "XGetSubImage",
        constants$4.XGetSubImage$FUNC, false
    );
    static final FunctionDescriptor XOpenDisplay$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XOpenDisplay$MH = RuntimeHelper.downcallHandle(
        "XOpenDisplay",
        constants$4.XOpenDisplay$FUNC, false
    );
    static final FunctionDescriptor XrmInitialize$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle XrmInitialize$MH = RuntimeHelper.downcallHandle(
        "XrmInitialize",
        constants$4.XrmInitialize$FUNC, false
    );
    static final FunctionDescriptor XFetchBytes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XFetchBytes$MH = RuntimeHelper.downcallHandle(
        "XFetchBytes",
        constants$4.XFetchBytes$FUNC, false
    );
}


