// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$172 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$172() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "XGrabPointer",
        constants$172.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "XGrabServer",
        constants$11.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "XHeightMMOfScreen",
        constants$11.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "XHeightOfScreen",
        constants$11.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(XIfEvent$x0.class, "apply", constants$113.const$3);
}


