// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final VarHandle const$0 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("dash_offset"));
    static final VarHandle const$1 = constants$13.const$2.varHandle(MemoryLayout.PathElement.groupElement("dashes"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("ext_data"),
        JAVA_LONG.withName("visualid"),
        JAVA_INT.withName("class"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("red_mask"),
        JAVA_LONG.withName("green_mask"),
        JAVA_LONG.withName("blue_mask"),
        JAVA_INT.withName("bits_per_rgb"),
        JAVA_INT.withName("map_entries")
    ).withName("");
    static final VarHandle const$3 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("ext_data"));
    static final VarHandle const$4 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("visualid"));
    static final VarHandle const$5 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("class"));
}


