// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int type;
 *     unsigned long serial;
 *     int send_event;
 *     Display* display;
 *     Window window;
 *     Colormap colormap;
 *     int new;
 *     int state;
 * };
 * }
 */
public class XColormapEvent {

    public static MemoryLayout $LAYOUT() {
        return constants$93.const$5;
    }
    public static VarHandle type$VH() {
        return constants$94.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$94.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$94.const$0.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$94.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$94.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle serial$VH() {
        return constants$94.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long serial;
     * }
     */
    public static long serial$get(MemorySegment seg) {
        return (long)constants$94.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long serial;
     * }
     */
    public static void serial$set(MemorySegment seg, long x) {
        constants$94.const$1.set(seg, x);
    }
    public static long serial$get(MemorySegment seg, long index) {
        return (long)constants$94.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void serial$set(MemorySegment seg, long index, long x) {
        constants$94.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle send_event$VH() {
        return constants$94.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int send_event;
     * }
     */
    public static int send_event$get(MemorySegment seg) {
        return (int)constants$94.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int send_event;
     * }
     */
    public static void send_event$set(MemorySegment seg, int x) {
        constants$94.const$2.set(seg, x);
    }
    public static int send_event$get(MemorySegment seg, long index) {
        return (int)constants$94.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void send_event$set(MemorySegment seg, long index, int x) {
        constants$94.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle display$VH() {
        return constants$94.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Display* display;
     * }
     */
    public static MemorySegment display$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$94.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Display* display;
     * }
     */
    public static void display$set(MemorySegment seg, MemorySegment x) {
        constants$94.const$3.set(seg, x);
    }
    public static MemorySegment display$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$94.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void display$set(MemorySegment seg, long index, MemorySegment x) {
        constants$94.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle window$VH() {
        return constants$94.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Window window;
     * }
     */
    public static long window$get(MemorySegment seg) {
        return (long)constants$94.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Window window;
     * }
     */
    public static void window$set(MemorySegment seg, long x) {
        constants$94.const$4.set(seg, x);
    }
    public static long window$get(MemorySegment seg, long index) {
        return (long)constants$94.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void window$set(MemorySegment seg, long index, long x) {
        constants$94.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle colormap$VH() {
        return constants$94.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Colormap colormap;
     * }
     */
    public static long colormap$get(MemorySegment seg) {
        return (long)constants$94.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Colormap colormap;
     * }
     */
    public static void colormap$set(MemorySegment seg, long x) {
        constants$94.const$5.set(seg, x);
    }
    public static long colormap$get(MemorySegment seg, long index) {
        return (long)constants$94.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void colormap$set(MemorySegment seg, long index, long x) {
        constants$94.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle new_$VH() {
        return constants$95.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int new;
     * }
     */
    public static int new_$get(MemorySegment seg) {
        return (int)constants$95.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int new;
     * }
     */
    public static void new_$set(MemorySegment seg, int x) {
        constants$95.const$0.set(seg, x);
    }
    public static int new_$get(MemorySegment seg, long index) {
        return (int)constants$95.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void new_$set(MemorySegment seg, long index, int x) {
        constants$95.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle state$VH() {
        return constants$95.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int state;
     * }
     */
    public static int state$get(MemorySegment seg) {
        return (int)constants$95.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int state;
     * }
     */
    public static void state$set(MemorySegment seg, int x) {
        constants$95.const$1.set(seg, x);
    }
    public static int state$get(MemorySegment seg, long index) {
        return (int)constants$95.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void state$set(MemorySegment seg, long index, int x) {
        constants$95.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


