// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int type;
 *     unsigned long serial;
 *     int send_event;
 *     Display* display;
 *     int extension;
 *     int evtype;
 *     unsigned int cookie;
 *     void* data;
 * };
 * }
 */
public class XGenericEventCookie {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("type"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_LONG_LONG$LAYOUT.withName("serial"),
        Constants$root.C_INT$LAYOUT.withName("send_event"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("display"),
        Constants$root.C_INT$LAYOUT.withName("extension"),
        Constants$root.C_INT$LAYOUT.withName("evtype"),
        Constants$root.C_INT$LAYOUT.withName("cookie"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("data")
    );
    public static MemoryLayout $LAYOUT() {
        return XGenericEventCookie.$struct$LAYOUT;
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return XGenericEventCookie.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)XGenericEventCookie.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        XGenericEventCookie.type$VH.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)XGenericEventCookie.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        XGenericEventCookie.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle serial$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("serial"));
    public static VarHandle serial$VH() {
        return XGenericEventCookie.serial$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long serial;
     * }
     */
    public static long serial$get(MemorySegment seg) {
        return (long)XGenericEventCookie.serial$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long serial;
     * }
     */
    public static void serial$set(MemorySegment seg, long x) {
        XGenericEventCookie.serial$VH.set(seg, x);
    }
    public static long serial$get(MemorySegment seg, long index) {
        return (long)XGenericEventCookie.serial$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void serial$set(MemorySegment seg, long index, long x) {
        XGenericEventCookie.serial$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle send_event$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("send_event"));
    public static VarHandle send_event$VH() {
        return XGenericEventCookie.send_event$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int send_event;
     * }
     */
    public static int send_event$get(MemorySegment seg) {
        return (int)XGenericEventCookie.send_event$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int send_event;
     * }
     */
    public static void send_event$set(MemorySegment seg, int x) {
        XGenericEventCookie.send_event$VH.set(seg, x);
    }
    public static int send_event$get(MemorySegment seg, long index) {
        return (int)XGenericEventCookie.send_event$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void send_event$set(MemorySegment seg, long index, int x) {
        XGenericEventCookie.send_event$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle display$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("display"));
    public static VarHandle display$VH() {
        return XGenericEventCookie.display$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Display* display;
     * }
     */
    public static MemorySegment display$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)XGenericEventCookie.display$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Display* display;
     * }
     */
    public static void display$set(MemorySegment seg, MemorySegment x) {
        XGenericEventCookie.display$VH.set(seg, x);
    }
    public static MemorySegment display$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)XGenericEventCookie.display$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void display$set(MemorySegment seg, long index, MemorySegment x) {
        XGenericEventCookie.display$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle extension$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("extension"));
    public static VarHandle extension$VH() {
        return XGenericEventCookie.extension$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int extension;
     * }
     */
    public static int extension$get(MemorySegment seg) {
        return (int)XGenericEventCookie.extension$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int extension;
     * }
     */
    public static void extension$set(MemorySegment seg, int x) {
        XGenericEventCookie.extension$VH.set(seg, x);
    }
    public static int extension$get(MemorySegment seg, long index) {
        return (int)XGenericEventCookie.extension$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void extension$set(MemorySegment seg, long index, int x) {
        XGenericEventCookie.extension$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle evtype$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("evtype"));
    public static VarHandle evtype$VH() {
        return XGenericEventCookie.evtype$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int evtype;
     * }
     */
    public static int evtype$get(MemorySegment seg) {
        return (int)XGenericEventCookie.evtype$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int evtype;
     * }
     */
    public static void evtype$set(MemorySegment seg, int x) {
        XGenericEventCookie.evtype$VH.set(seg, x);
    }
    public static int evtype$get(MemorySegment seg, long index) {
        return (int)XGenericEventCookie.evtype$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void evtype$set(MemorySegment seg, long index, int x) {
        XGenericEventCookie.evtype$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle cookie$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("cookie"));
    public static VarHandle cookie$VH() {
        return XGenericEventCookie.cookie$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int cookie;
     * }
     */
    public static int cookie$get(MemorySegment seg) {
        return (int)XGenericEventCookie.cookie$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int cookie;
     * }
     */
    public static void cookie$set(MemorySegment seg, int x) {
        XGenericEventCookie.cookie$VH.set(seg, x);
    }
    public static int cookie$get(MemorySegment seg, long index) {
        return (int)XGenericEventCookie.cookie$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void cookie$set(MemorySegment seg, long index, int x) {
        XGenericEventCookie.cookie$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data"));
    public static VarHandle data$VH() {
        return XGenericEventCookie.data$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static MemorySegment data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)XGenericEventCookie.data$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* data;
     * }
     */
    public static void data$set(MemorySegment seg, MemorySegment x) {
        XGenericEventCookie.data$VH.set(seg, x);
    }
    public static MemorySegment data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)XGenericEventCookie.data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemorySegment x) {
        XGenericEventCookie.data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


