// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class XIMCallback {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("client_data"),
        Constants$root.C_POINTER$LAYOUT.withName("callback")
    );
    public static MemoryLayout $LAYOUT() {
        return XIMCallback.$struct$LAYOUT;
    }
    static final VarHandle client_data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("client_data"));
    public static VarHandle client_data$VH() {
        return XIMCallback.client_data$VH;
    }
    public static MemoryAddress client_data$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)XIMCallback.client_data$VH.get(seg);
    }
    public static void client_data$set( MemorySegment seg, MemoryAddress x) {
        XIMCallback.client_data$VH.set(seg, x);
    }
    public static MemoryAddress client_data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)XIMCallback.client_data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void client_data$set(MemorySegment seg, long index, MemoryAddress x) {
        XIMCallback.client_data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle callback$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("callback"));
    public static VarHandle callback$VH() {
        return XIMCallback.callback$VH;
    }
    public static MemoryAddress callback$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)XIMCallback.callback$VH.get(seg);
    }
    public static void callback$set( MemorySegment seg, MemoryAddress x) {
        XIMCallback.callback$VH.set(seg, x);
    }
    public static MemoryAddress callback$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)XIMCallback.callback$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void callback$set(MemorySegment seg, long index, MemoryAddress x) {
        XIMCallback.callback$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static XIMProc callback (MemorySegment segment, MemorySession session) {
        return XIMProc.ofAddress(callback$get(segment), session);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


