// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _XIMStatusDrawCallbackStruct {
 *     XIMStatusDataType type;
 *     union {
 *         XIMText *text;
 *         Pixmap bitmap;
 *     } data;
 * } XIMStatusDrawCallbackStruct
 * }
 */
public class XIMStatusDrawCallbackStruct extends _XIMStatusDrawCallbackStruct {

    XIMStatusDrawCallbackStruct() {
        // Should not be called directly
    }
}

