// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class Xlib_h_3 extends Xlib_h_2 {

    /**
     * {@snippet :
     * #define CWWinGravity 32
     * }
     */
    public static long CWWinGravity() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define CWBackingStore 64
     * }
     */
    public static long CWBackingStore() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define CWBackingPlanes 128
     * }
     */
    public static long CWBackingPlanes() {
        return 128L;
    }
    /**
     * {@snippet :
     * #define CWBackingPixel 256
     * }
     */
    public static long CWBackingPixel() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define CWOverrideRedirect 512
     * }
     */
    public static long CWOverrideRedirect() {
        return 512L;
    }
    /**
     * {@snippet :
     * #define CWSaveUnder 1024
     * }
     */
    public static long CWSaveUnder() {
        return 1024L;
    }
    /**
     * {@snippet :
     * #define CWEventMask 2048
     * }
     */
    public static long CWEventMask() {
        return 2048L;
    }
    /**
     * {@snippet :
     * #define CWDontPropagate 4096
     * }
     */
    public static long CWDontPropagate() {
        return 4096L;
    }
    /**
     * {@snippet :
     * #define CWColormap 8192
     * }
     */
    public static long CWColormap() {
        return 8192L;
    }
    /**
     * {@snippet :
     * #define CWCursor 16384
     * }
     */
    public static long CWCursor() {
        return 16384L;
    }
    /**
     * {@snippet :
     * #define CWX 1
     * }
     */
    public static int CWX() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define CWY 2
     * }
     */
    public static int CWY() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define CWWidth 4
     * }
     */
    public static int CWWidth() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define CWHeight 8
     * }
     */
    public static int CWHeight() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define CWBorderWidth 16
     * }
     */
    public static int CWBorderWidth() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define CWSibling 32
     * }
     */
    public static int CWSibling() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define CWStackMode 64
     * }
     */
    public static int CWStackMode() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define GCFunction 1
     * }
     */
    public static long GCFunction() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define GCPlaneMask 2
     * }
     */
    public static long GCPlaneMask() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define GCForeground 4
     * }
     */
    public static long GCForeground() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define GCBackground 8
     * }
     */
    public static long GCBackground() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define GCLineWidth 16
     * }
     */
    public static long GCLineWidth() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define GCLineStyle 32
     * }
     */
    public static long GCLineStyle() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define GCCapStyle 64
     * }
     */
    public static long GCCapStyle() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define GCJoinStyle 128
     * }
     */
    public static long GCJoinStyle() {
        return 128L;
    }
    /**
     * {@snippet :
     * #define GCFillStyle 256
     * }
     */
    public static long GCFillStyle() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define GCFillRule 512
     * }
     */
    public static long GCFillRule() {
        return 512L;
    }
    /**
     * {@snippet :
     * #define GCTile 1024
     * }
     */
    public static long GCTile() {
        return 1024L;
    }
    /**
     * {@snippet :
     * #define GCStipple 2048
     * }
     */
    public static long GCStipple() {
        return 2048L;
    }
    /**
     * {@snippet :
     * #define GCTileStipXOrigin 4096
     * }
     */
    public static long GCTileStipXOrigin() {
        return 4096L;
    }
    /**
     * {@snippet :
     * #define GCTileStipYOrigin 8192
     * }
     */
    public static long GCTileStipYOrigin() {
        return 8192L;
    }
    /**
     * {@snippet :
     * #define GCFont 16384
     * }
     */
    public static long GCFont() {
        return 16384L;
    }
    /**
     * {@snippet :
     * #define GCSubwindowMode 32768
     * }
     */
    public static long GCSubwindowMode() {
        return 32768L;
    }
    /**
     * {@snippet :
     * #define GCGraphicsExposures 65536
     * }
     */
    public static long GCGraphicsExposures() {
        return 65536L;
    }
    /**
     * {@snippet :
     * #define GCClipXOrigin 131072
     * }
     */
    public static long GCClipXOrigin() {
        return 131072L;
    }
    /**
     * {@snippet :
     * #define GCClipYOrigin 262144
     * }
     */
    public static long GCClipYOrigin() {
        return 262144L;
    }
    /**
     * {@snippet :
     * #define GCClipMask 524288
     * }
     */
    public static long GCClipMask() {
        return 524288L;
    }
    /**
     * {@snippet :
     * #define GCDashOffset 1048576
     * }
     */
    public static long GCDashOffset() {
        return 1048576L;
    }
    /**
     * {@snippet :
     * #define GCDashList 2097152
     * }
     */
    public static long GCDashList() {
        return 2097152L;
    }
    /**
     * {@snippet :
     * #define GCArcMode 4194304
     * }
     */
    public static long GCArcMode() {
        return 4194304L;
    }
    /**
     * {@snippet :
     * #define DoRed 1
     * }
     */
    public static int DoRed() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define DoGreen 2
     * }
     */
    public static int DoGreen() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define DoBlue 4
     * }
     */
    public static int DoBlue() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define KBKeyClickPercent 1
     * }
     */
    public static long KBKeyClickPercent() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define KBBellPercent 2
     * }
     */
    public static long KBBellPercent() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define KBBellPitch 4
     * }
     */
    public static long KBBellPitch() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define KBBellDuration 8
     * }
     */
    public static long KBBellDuration() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define KBLed 16
     * }
     */
    public static long KBLed() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define KBLedMode 32
     * }
     */
    public static long KBLedMode() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define KBKey 64
     * }
     */
    public static long KBKey() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define KBAutoRepeatMode 128
     * }
     */
    public static long KBAutoRepeatMode() {
        return 128L;
    }
    /**
     * {@snippet :
     * #define NULL 0
     * }
     */
    public static MemorySegment NULL() {
        return constants$236.const$1;
    }
    /**
     * {@snippet :
     * #define AllPlanes -1
     * }
     */
    public static long AllPlanes() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define XNRequiredCharSet "requiredCharSet"
     * }
     */
    public static MemorySegment XNRequiredCharSet() {
        return constants$236.const$2;
    }
    /**
     * {@snippet :
     * #define XNQueryOrientation "queryOrientation"
     * }
     */
    public static MemorySegment XNQueryOrientation() {
        return constants$236.const$3;
    }
    /**
     * {@snippet :
     * #define XNBaseFontName "baseFontName"
     * }
     */
    public static MemorySegment XNBaseFontName() {
        return constants$236.const$4;
    }
    /**
     * {@snippet :
     * #define XNOMAutomatic "omAutomatic"
     * }
     */
    public static MemorySegment XNOMAutomatic() {
        return constants$236.const$5;
    }
    /**
     * {@snippet :
     * #define XNMissingCharSet "missingCharSet"
     * }
     */
    public static MemorySegment XNMissingCharSet() {
        return constants$237.const$0;
    }
    /**
     * {@snippet :
     * #define XNDefaultString "defaultString"
     * }
     */
    public static MemorySegment XNDefaultString() {
        return constants$237.const$1;
    }
    /**
     * {@snippet :
     * #define XNOrientation "orientation"
     * }
     */
    public static MemorySegment XNOrientation() {
        return constants$237.const$2;
    }
    /**
     * {@snippet :
     * #define XNDirectionalDependentDrawing "directionalDependentDrawing"
     * }
     */
    public static MemorySegment XNDirectionalDependentDrawing() {
        return constants$237.const$3;
    }
    /**
     * {@snippet :
     * #define XNContextualDrawing "contextualDrawing"
     * }
     */
    public static MemorySegment XNContextualDrawing() {
        return constants$237.const$4;
    }
    /**
     * {@snippet :
     * #define XNFontInfo "fontInfo"
     * }
     */
    public static MemorySegment XNFontInfo() {
        return constants$237.const$5;
    }
    /**
     * {@snippet :
     * #define XIMPreeditArea 1
     * }
     */
    public static long XIMPreeditArea() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditCallbacks 2
     * }
     */
    public static long XIMPreeditCallbacks() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditPosition 4
     * }
     */
    public static long XIMPreeditPosition() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditNothing 8
     * }
     */
    public static long XIMPreeditNothing() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditNone 16
     * }
     */
    public static long XIMPreeditNone() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define XIMStatusArea 256
     * }
     */
    public static long XIMStatusArea() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define XIMStatusCallbacks 512
     * }
     */
    public static long XIMStatusCallbacks() {
        return 512L;
    }
    /**
     * {@snippet :
     * #define XIMStatusNothing 1024
     * }
     */
    public static long XIMStatusNothing() {
        return 1024L;
    }
    /**
     * {@snippet :
     * #define XIMStatusNone 2048
     * }
     */
    public static long XIMStatusNone() {
        return 2048L;
    }
    /**
     * {@snippet :
     * #define XNVaNestedList "XNVaNestedList"
     * }
     */
    public static MemorySegment XNVaNestedList() {
        return constants$238.const$0;
    }
    /**
     * {@snippet :
     * #define XNQueryInputStyle "queryInputStyle"
     * }
     */
    public static MemorySegment XNQueryInputStyle() {
        return constants$238.const$1;
    }
    /**
     * {@snippet :
     * #define XNClientWindow "clientWindow"
     * }
     */
    public static MemorySegment XNClientWindow() {
        return constants$238.const$2;
    }
    /**
     * {@snippet :
     * #define XNInputStyle "inputStyle"
     * }
     */
    public static MemorySegment XNInputStyle() {
        return constants$238.const$3;
    }
    /**
     * {@snippet :
     * #define XNFocusWindow "focusWindow"
     * }
     */
    public static MemorySegment XNFocusWindow() {
        return constants$238.const$4;
    }
    /**
     * {@snippet :
     * #define XNResourceName "resourceName"
     * }
     */
    public static MemorySegment XNResourceName() {
        return constants$238.const$5;
    }
    /**
     * {@snippet :
     * #define XNResourceClass "resourceClass"
     * }
     */
    public static MemorySegment XNResourceClass() {
        return constants$239.const$0;
    }
    /**
     * {@snippet :
     * #define XNGeometryCallback "geometryCallback"
     * }
     */
    public static MemorySegment XNGeometryCallback() {
        return constants$239.const$1;
    }
    /**
     * {@snippet :
     * #define XNDestroyCallback "destroyCallback"
     * }
     */
    public static MemorySegment XNDestroyCallback() {
        return constants$239.const$2;
    }
    /**
     * {@snippet :
     * #define XNFilterEvents "filterEvents"
     * }
     */
    public static MemorySegment XNFilterEvents() {
        return constants$239.const$3;
    }
    /**
     * {@snippet :
     * #define XNPreeditStartCallback "preeditStartCallback"
     * }
     */
    public static MemorySegment XNPreeditStartCallback() {
        return constants$239.const$4;
    }
    /**
     * {@snippet :
     * #define XNPreeditDoneCallback "preeditDoneCallback"
     * }
     */
    public static MemorySegment XNPreeditDoneCallback() {
        return constants$239.const$5;
    }
    /**
     * {@snippet :
     * #define XNPreeditDrawCallback "preeditDrawCallback"
     * }
     */
    public static MemorySegment XNPreeditDrawCallback() {
        return constants$240.const$0;
    }
    /**
     * {@snippet :
     * #define XNPreeditCaretCallback "preeditCaretCallback"
     * }
     */
    public static MemorySegment XNPreeditCaretCallback() {
        return constants$240.const$1;
    }
    /**
     * {@snippet :
     * #define XNPreeditStateNotifyCallback "preeditStateNotifyCallback"
     * }
     */
    public static MemorySegment XNPreeditStateNotifyCallback() {
        return constants$240.const$2;
    }
    /**
     * {@snippet :
     * #define XNPreeditAttributes "preeditAttributes"
     * }
     */
    public static MemorySegment XNPreeditAttributes() {
        return constants$240.const$3;
    }
    /**
     * {@snippet :
     * #define XNStatusStartCallback "statusStartCallback"
     * }
     */
    public static MemorySegment XNStatusStartCallback() {
        return constants$240.const$4;
    }
    /**
     * {@snippet :
     * #define XNStatusDoneCallback "statusDoneCallback"
     * }
     */
    public static MemorySegment XNStatusDoneCallback() {
        return constants$240.const$5;
    }
    /**
     * {@snippet :
     * #define XNStatusDrawCallback "statusDrawCallback"
     * }
     */
    public static MemorySegment XNStatusDrawCallback() {
        return constants$241.const$0;
    }
    /**
     * {@snippet :
     * #define XNStatusAttributes "statusAttributes"
     * }
     */
    public static MemorySegment XNStatusAttributes() {
        return constants$241.const$1;
    }
    /**
     * {@snippet :
     * #define XNArea "area"
     * }
     */
    public static MemorySegment XNArea() {
        return constants$241.const$2;
    }
    /**
     * {@snippet :
     * #define XNAreaNeeded "areaNeeded"
     * }
     */
    public static MemorySegment XNAreaNeeded() {
        return constants$241.const$3;
    }
    /**
     * {@snippet :
     * #define XNSpotLocation "spotLocation"
     * }
     */
    public static MemorySegment XNSpotLocation() {
        return constants$241.const$4;
    }
    /**
     * {@snippet :
     * #define XNColormap "colorMap"
     * }
     */
    public static MemorySegment XNColormap() {
        return constants$241.const$5;
    }
    /**
     * {@snippet :
     * #define XNStdColormap "stdColorMap"
     * }
     */
    public static MemorySegment XNStdColormap() {
        return constants$242.const$0;
    }
    /**
     * {@snippet :
     * #define XNForeground "foreground"
     * }
     */
    public static MemorySegment XNForeground() {
        return constants$242.const$1;
    }
    /**
     * {@snippet :
     * #define XNBackground "background"
     * }
     */
    public static MemorySegment XNBackground() {
        return constants$242.const$2;
    }
    /**
     * {@snippet :
     * #define XNBackgroundPixmap "backgroundPixmap"
     * }
     */
    public static MemorySegment XNBackgroundPixmap() {
        return constants$242.const$3;
    }
    /**
     * {@snippet :
     * #define XNFontSet "fontSet"
     * }
     */
    public static MemorySegment XNFontSet() {
        return constants$242.const$4;
    }
    /**
     * {@snippet :
     * #define XNLineSpace "lineSpace"
     * }
     */
    public static MemorySegment XNLineSpace() {
        return constants$242.const$5;
    }
    /**
     * {@snippet :
     * #define XNCursor "cursor"
     * }
     */
    public static MemorySegment XNCursor() {
        return constants$243.const$0;
    }
    /**
     * {@snippet :
     * #define XNQueryIMValuesList "queryIMValuesList"
     * }
     */
    public static MemorySegment XNQueryIMValuesList() {
        return constants$243.const$1;
    }
    /**
     * {@snippet :
     * #define XNQueryICValuesList "queryICValuesList"
     * }
     */
    public static MemorySegment XNQueryICValuesList() {
        return constants$243.const$2;
    }
    /**
     * {@snippet :
     * #define XNVisiblePosition "visiblePosition"
     * }
     */
    public static MemorySegment XNVisiblePosition() {
        return constants$243.const$3;
    }
    /**
     * {@snippet :
     * #define XNR6PreeditCallback "r6PreeditCallback"
     * }
     */
    public static MemorySegment XNR6PreeditCallback() {
        return constants$243.const$4;
    }
    /**
     * {@snippet :
     * #define XNStringConversionCallback "stringConversionCallback"
     * }
     */
    public static MemorySegment XNStringConversionCallback() {
        return constants$243.const$5;
    }
    /**
     * {@snippet :
     * #define XNStringConversion "stringConversion"
     * }
     */
    public static MemorySegment XNStringConversion() {
        return constants$244.const$0;
    }
    /**
     * {@snippet :
     * #define XNResetState "resetState"
     * }
     */
    public static MemorySegment XNResetState() {
        return constants$244.const$1;
    }
    /**
     * {@snippet :
     * #define XNHotKey "hotKey"
     * }
     */
    public static MemorySegment XNHotKey() {
        return constants$244.const$2;
    }
    /**
     * {@snippet :
     * #define XNHotKeyState "hotKeyState"
     * }
     */
    public static MemorySegment XNHotKeyState() {
        return constants$244.const$3;
    }
    /**
     * {@snippet :
     * #define XNPreeditState "preeditState"
     * }
     */
    public static MemorySegment XNPreeditState() {
        return constants$244.const$4;
    }
    /**
     * {@snippet :
     * #define XNSeparatorofNestedList "separatorofNestedList"
     * }
     */
    public static MemorySegment XNSeparatorofNestedList() {
        return constants$244.const$5;
    }
    /**
     * {@snippet :
     * #define XBufferOverflow -1
     * }
     */
    public static int XBufferOverflow() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define XIMReverse 1
     * }
     */
    public static long XIMReverse() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define XIMUnderline 2
     * }
     */
    public static long XIMUnderline() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define XIMHighlight 4
     * }
     */
    public static long XIMHighlight() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define XIMPrimary 32
     * }
     */
    public static long XIMPrimary() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define XIMSecondary 64
     * }
     */
    public static long XIMSecondary() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define XIMTertiary 128
     * }
     */
    public static long XIMTertiary() {
        return 128L;
    }
    /**
     * {@snippet :
     * #define XIMVisibleToForward 256
     * }
     */
    public static long XIMVisibleToForward() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define XIMVisibleToBackword 512
     * }
     */
    public static long XIMVisibleToBackword() {
        return 512L;
    }
    /**
     * {@snippet :
     * #define XIMVisibleToCenter 1024
     * }
     */
    public static long XIMVisibleToCenter() {
        return 1024L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditUnKnown 0
     * }
     */
    public static long XIMPreeditUnKnown() {
        return 0L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditEnable 1
     * }
     */
    public static long XIMPreeditEnable() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define XIMPreeditDisable 2
     * }
     */
    public static long XIMPreeditDisable() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define XIMInitialState 1
     * }
     */
    public static long XIMInitialState() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define XIMPreserveState 2
     * }
     */
    public static long XIMPreserveState() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionLeftEdge 1
     * }
     */
    public static int XIMStringConversionLeftEdge() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionRightEdge 2
     * }
     */
    public static int XIMStringConversionRightEdge() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionTopEdge 4
     * }
     */
    public static int XIMStringConversionTopEdge() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionBottomEdge 8
     * }
     */
    public static int XIMStringConversionBottomEdge() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionConcealed 16
     * }
     */
    public static int XIMStringConversionConcealed() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionWrapped 32
     * }
     */
    public static int XIMStringConversionWrapped() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionBuffer 1
     * }
     */
    public static int XIMStringConversionBuffer() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionLine 2
     * }
     */
    public static int XIMStringConversionLine() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionWord 3
     * }
     */
    public static int XIMStringConversionWord() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionChar 4
     * }
     */
    public static int XIMStringConversionChar() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionSubstitution 1
     * }
     */
    public static int XIMStringConversionSubstitution() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define XIMStringConversionRetrieval 2
     * }
     */
    public static int XIMStringConversionRetrieval() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define XIMHotKeyStateON 1
     * }
     */
    public static long XIMHotKeyStateON() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define XIMHotKeyStateOFF 2
     * }
     */
    public static long XIMHotKeyStateOFF() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define USPosition 1
     * }
     */
    public static long USPosition() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define USSize 2
     * }
     */
    public static long USSize() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define PPosition 4
     * }
     */
    public static long PPosition() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define PSize 8
     * }
     */
    public static long PSize() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define PMinSize 16
     * }
     */
    public static long PMinSize() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define PMaxSize 32
     * }
     */
    public static long PMaxSize() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define PResizeInc 64
     * }
     */
    public static long PResizeInc() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define PAspect 128
     * }
     */
    public static long PAspect() {
        return 128L;
    }
    /**
     * {@snippet :
     * #define PBaseSize 256
     * }
     */
    public static long PBaseSize() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define PWinGravity 512
     * }
     */
    public static long PWinGravity() {
        return 512L;
    }
    /**
     * {@snippet :
     * #define PAllHints 252
     * }
     */
    public static long PAllHints() {
        return 252L;
    }
    /**
     * {@snippet :
     * #define InputHint 1
     * }
     */
    public static long InputHint() {
        return 1L;
    }
    /**
     * {@snippet :
     * #define StateHint 2
     * }
     */
    public static long StateHint() {
        return 2L;
    }
    /**
     * {@snippet :
     * #define IconPixmapHint 4
     * }
     */
    public static long IconPixmapHint() {
        return 4L;
    }
    /**
     * {@snippet :
     * #define IconWindowHint 8
     * }
     */
    public static long IconWindowHint() {
        return 8L;
    }
    /**
     * {@snippet :
     * #define IconPositionHint 16
     * }
     */
    public static long IconPositionHint() {
        return 16L;
    }
    /**
     * {@snippet :
     * #define IconMaskHint 32
     * }
     */
    public static long IconMaskHint() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define WindowGroupHint 64
     * }
     */
    public static long WindowGroupHint() {
        return 64L;
    }
    /**
     * {@snippet :
     * #define AllHints 127
     * }
     */
    public static long AllHints() {
        return 127L;
    }
    /**
     * {@snippet :
     * #define XUrgencyHint 256
     * }
     */
    public static long XUrgencyHint() {
        return 256L;
    }
    /**
     * {@snippet :
     * #define XNoMemory -1
     * }
     */
    public static int XNoMemory() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define XLocaleNotSupported -2
     * }
     */
    public static int XLocaleNotSupported() {
        return (int)-2L;
    }
    /**
     * {@snippet :
     * #define XConverterNotFound -3
     * }
     */
    public static int XConverterNotFound() {
        return (int)-3L;
    }
    /**
     * {@snippet :
     * #define ReleaseByFreeingColormap 1
     * }
     */
    public static long ReleaseByFreeingColormap() {
        return 1L;
    }
}


