// Generated by jextract

package tech.bitey.golpanama.xlib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int num_orientation;
 *     XOrientation* orientation;
 * };
 * }
 */
public class XOMOrientation {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("num_orientation"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("orientation")
    );
    public static MemoryLayout $LAYOUT() {
        return XOMOrientation.$struct$LAYOUT;
    }
    static final VarHandle num_orientation$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num_orientation"));
    public static VarHandle num_orientation$VH() {
        return XOMOrientation.num_orientation$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int num_orientation;
     * }
     */
    public static int num_orientation$get(MemorySegment seg) {
        return (int)XOMOrientation.num_orientation$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int num_orientation;
     * }
     */
    public static void num_orientation$set(MemorySegment seg, int x) {
        XOMOrientation.num_orientation$VH.set(seg, x);
    }
    public static int num_orientation$get(MemorySegment seg, long index) {
        return (int)XOMOrientation.num_orientation$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num_orientation$set(MemorySegment seg, long index, int x) {
        XOMOrientation.num_orientation$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle orientation$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("orientation"));
    public static VarHandle orientation$VH() {
        return XOMOrientation.orientation$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * XOrientation* orientation;
     * }
     */
    public static MemorySegment orientation$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)XOMOrientation.orientation$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * XOrientation* orientation;
     * }
     */
    public static void orientation$set(MemorySegment seg, MemorySegment x) {
        XOMOrientation.orientation$VH.set(seg, x);
    }
    public static MemorySegment orientation$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)XOMOrientation.orientation$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void orientation$set(MemorySegment seg, long index, MemorySegment x) {
        XOMOrientation.orientation$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


